spring:
  application:
    name: pokedex
  web:
    resources:
      static-locations: classpath:/Frontend/


  data:
    mongodb:
      uri: mongodb+srv://pokedex694:pokedex123@pokedex.6anix.mongodb.net/pokedex?retryWrites=true&w=majority&appName=POKEDEX

