spring:
  application:
    name: pokedex

  data:
    mongodb:
      uri: mongodb+srv://pokedex694:pokedex123@pokedex.6anix.mongodb.net/pokedex?retryWrites=true&w=majority&appName=POKEDEX

  profiles:
      active: dev

  # Configuration du serveur de messagerie
  mail:
    host: localhost
    port: 9025

# Configuration du port du serveur de l'application et du du chemin de mes url pour qu'il commmence par api
server:
  servlet:
    context-path: /api
