name: Backend CI/CD

on:
  push:
    branches:
      - main   # 当推送到 main 分支时触发

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Java 环境
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17

      # 3. 构建 Spring Boot 应用
      - name: Build backend
        run: |
          cd backend
          ./mvnw clean package -DskipTests

      # 4. 构建并推送后端 Docker 镜像
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t yuan1216/backend:latest ./backend
          echo "Lorna001216" | docker login -u "yuan1216" --password-stdin
          docker push yuan1216/backend:latest
